### ISSUE TITLE
why should a puzzle print hints. too ez

### ISSUE THREAD

**Issue by jonathanli2012** [janwucmu/Picture-Cross-Solver#1]
https://github.com/janwucmu/Picture-Cross-Solver/blob/bec28fdf20cf4f1df43a04f9ddff7852c4f277e1/code/solver.cpp#L39

**Comment by gorangor** [comment]
You're right, we will remove it in version 0.2. Thank you for your feedback, its because of community members like you that "Picture Cross Solver by janwucmu" will be the best picture cross solver in the country!
